name       : cuetools
version    : 1.4.1
release    : 1
source     :
    - https://github.com/svend/cuetools/archive/1.4.1.tar.gz : 24a2420f100c69a6539a9feeb4130d19532f9f8a0428a8b9b289c6da761eb107
license    : GPL-2.0
component  : multimedia.audio
summary    : Cue and toc file parsers and utilities
description: |
    Cuetools is a set of utilities for working with Cue Sheet (cue) and Table of 
    Contents (toc) files. It includes programs for conversion between the formats,
    file renaming based on cue/toc information, and track breakpoint printing.
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
